### PR TITLE
Fix network aware node issue

### PR DESCRIPTION
**Pull request by ivanpauno**
Fixes https://github.com/ros2/ros2cli/issues/736.
https://github.com/ros2/ros2cli/commit/1195df07b48b048fee255ea83160c43275b785be fixes an issue introduced in https://github.com/ros2/ros2cli/pull/652. See https://github.com/ros2/ros2cli/issues/736#issuecomment-1200673304.
https://github.com/ros2/ros2cli/commit/77c5f6c20f1f35881505db5f9d553a71646a6e5f corrects how netifaces is being used (improves the checking it's being done).

### CODE REVIEW

**Review by fujitatomoya — APPROVED** [review]
lgtm

**Comment by ivanpauno** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17836/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12404/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18503/)

**Comment by fujitatomoya** [comment]
@ivanpauno do we want to backport this to humble? i think it would be helpful for user experience.

**Comment by ivanpauno** [comment]
Yes, let's wait one week to see if nightlies are still green, I will backport then.

**Comment by ivanpauno** [comment]
@mergifyio backport humble

**Pull request merged**
