### PR TITLE
[foxy] bugfix for #563 (#570)

### PR DESCRIPTION
**Pull request by fujitatomoya**
address https://github.com/ros2/ros2cli/issues/607 (backport of https://github.com/ros2/ros2cli/pull/570)

Signed-off-by: Daisuke Sato <daisukes@cmu.edu>

### CODE REVIEW

**Comment by fujitatomoya** [comment]
CC: @daisukes

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13940/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8781/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11644/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14028/)

**Comment by fujitatomoya** [comment]
@clalancette 

CI warnings are not related, could you help me to merge this into foxy?

**Review by audrow — APPROVED** [review]
Looks good to me.

**Pull request merged**
