### PR TITLE
Use set_message_fields from rosidl_runtime_py

### PR DESCRIPTION
**Pull request by esteve**
This PR is pending ros2/rosidl_runtime_py#19

### CODE REVIEW

**Comment by esteve** [comment]
@fujitatomoya @ivanpauno https://github.com/ros2/rosidl_runtime_py/pull/19 has been merged and a new release of `rosidl_runtime_py` has been tagged, so this PR now ready for review

**Review by ivanpauno — APPROVED** [review]
LGTM!

**Comment by ivanpauno** [comment]
@ros-pull-request-builder retest this please

**Comment by ivanpauno** [comment]
I'm not sure what's going on with the Rpr job, but it's probably unrelated.

**Comment by ivanpauno** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17295/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11836/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17782/)

**Comment by clalancette** [comment]
> I'm not sure what's going on with the Rpr job, but it's probably unrelated.

We're currently in the middle of a large rebuild of Rolling, so that's what is causing it.  It will probably take most of the day to complete.

**Comment by ivanpauno** [comment]
@ros-pull-request-builder retest this please

**Pull request merged**
