### PR TITLE
add yaml dump flow style.

### PR DESCRIPTION
**Pull request by fujitatomoya**
address https://github.com/ros2/ros2cli/issues/680

Signed-off-by: Tomoya Fujita <Tomoya.Fujita@sony.com>

### CODE REVIEW

**Comment by fujitatomoya** [comment]
this is supposed to fail since this depends on https://github.com/ros2/rosidl_runtime_py/pull/16

**Comment by fujitatomoya** [comment]
@iuhilnehc-ynos @audrow could you review this?

**Review by iuhilnehc-ynos — APPROVED** [review]

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16292/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10912/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16659/)

**Review by audrow — APPROVED** [review]
Looks good to me with green CI.

**Comment by fujitatomoya** [comment]
CI (retry):
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16323/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10943/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16693/)

**Comment by fujitatomoya** [comment]
CI: i do not have any error in my local environment.
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16324/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10944/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16694/)

**Comment by fujitatomoya** [comment]
@audrow @iuhilnehc-ynos CI is green, i will merge this.

**Comment by audrow** [comment]
I'm going to go ahead and merge this - since CI is green and PR jobs are broken, at the moment.

**Comment by fujitatomoya** [comment]
@audrow i do not think this PR has any merge conflicts?

**Comment by audrow** [comment]
@fujitatomoya Oops, you're right. I'll merge this in. Thanks for the PR!

**Pull request merged**
