### PR TITLE
replace removeprefix with string slicing.

### LINKED ISSUE #909: removeprefix breaks compatibility with source builds on Nvidia Jetson
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
  - Nvidia JetPack 5.1.1
  - Jetson Linux 35.3.1
- Installation type:
  - from source
- Version or commit hash:
  - 0c8ae6d976e2fdca1b109f5cb5e330691fe26fa0
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue
```
ros2 topic list
```

#### Expected behavior
Issued command works.

#### Actual behavior
```
Traceback (most recent call last):
  File "/opt/ros/humble/install/bin/ros2", line 33, in <module>
    sys.exit(load_entry_point('ros2cli==0.18.10', 'console_scripts', 'ros2')())
  File "/opt/ros/humble/install/lib/python3.8/site-packages/ros2cli/cli.py", line 91, in main
    rc = extension.main(parser=parser, args=args)
  File "/opt/ros/humble/install/lib/python3.8/site-packages/ros2topic/command/topic.py", line 41, in main
    return extension.main(args=args)
  File "/opt/ros/humble/install/lib/python3.8/site-packages/ros2topic/verb/list.py", line 55, in main
    with NodeStrategy(args) as node:
  File "/opt/ros/humble/install/lib/python3.8/site-packages/ros2cli/node/strategy.py", line 35, in __init__
    spawn_daemon(args)
  File "/opt/ros/humble/install/lib/python3.8/site-packages/ros2cli/node/daemon.py", line 148, in spawn_daemon
    fdlimit = int(line.removeprefix(string_to_find).strip())
AttributeError: 'str' object has no attribute 'removeprefix'
```

#### Additional information
Humble Hawksbill source builds are possible on Nvidia Jetson boards using JetPack 5.x, which is based on Ubuntu 20.04.
JetPack 5.x's Python version is 3.8, but `removeprefix` was added in Python version 3.9.

### PR DESCRIPTION
**Pull request by fujitatomoya**
closes https://github.com/ros2/ros2cli/issues/909

### CODE REVIEW

**Review by fujitatomoya — COMMENTED** [review]
@clalancette @ahcorde requesting review.

**Review by clalancette — APPROVED** [review]
Looks good to me with green CI.

**Comment by fujitatomoya** [comment]
Pulls: ros2/ros2cli#953
Gist: https://gist.githubusercontent.com/fujitatomoya/fb544178fb206617fd328f441858d411/raw/2ac39389bf07a1976d43ef60337e5fd715590ce8/ros2.repos
BUILD args:  --packages-above-and-dependencies ros2cli
TEST args:  --packages-above ros2cli
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14953
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/22265/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16526/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1788/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/23048/)

**Comment by fujitatomoya** [comment]
I really do not think the following access violation is generated by this PR.

```bash
--- stderr: test_launch_ros
01:30:33 Windows fatal exception: access violation
01:30:33 
01:30:33 Thread 0x00002ad4 (most recent call first):
01:30:33   File "C:\ci\ws\install\Lib\site-packages\rclpy\executors.py", line 718 in _wait_for_ready_callbacks
01:30:33   File "C:\ci\ws\install\Lib\site-packages\rclpy\executors.py", line 814 in wait_for_ready_callbacks
01:30:33   File "C:\ci\ws\install\Lib\site-packages\rclpy\executors.py", line 844 in _spin_once_impl
01:30:33   File "C:\ci\ws\install\Lib\site-packages\rclpy\executors.py", line 860 in spin_once
01:30:33   File "C:\ci\ws\install\Lib\site-packages\launch_ros\ros_adapters.py", line 77 in _run
01:30:33   File "C:\Python38\lib\threading.py", line 870 in run
01:30:33   File "C:\Python38\lib\threading.py", line 932 in _bootstrap_inner
01:30:33   File "C:\Python38\lib\threading.py", line 890 in _bootstrap
```

retry CI windows.

* Windows [Build Status](http://ci.ros2.org/job/ci_windows/23056/)

**Comment by fujitatomoya** [comment]
this is originally required for already released distros.

@Mergifyio backport humble jazzy

**Comment by clalancette** [comment]
@Mergifyio backport humble jazzy

**Pull request merged**
