### PR TITLE
add slash for node name

### PR DESCRIPTION
**Pull request by Karsten1987**
same fix as for get: https://github.com/ros2/ros2cli/pull/174

### CODE REVIEW

**Comment by Karsten1987** [comment]
the latest commit (https://github.com/ros2/ros2cli/pull/179/commits/be9e65a45d490b387c90f362305ca6d370cc7ac9) should also address https://github.com/ros2/ros2cli/issues/178

**Comment by nuclearsandwich** [comment]
It seems a bit odd to make this same transformation in every different verb. Is there a reason not to create a `normalize_node_name` or somesuch function?

**Comment by Karsten1987** [comment]
that is correct. I think we should actually have a function for this in rcl expanding the node name in a similar fashion as we do with topics (see https://github.com/ros2/rcl/blob/master/rcl/include/rcl/expand_topic_name.h) But given the time, I opted for this solution.

**Comment by wjwwood** [comment]
There could be a function to do this in rcl and it could be exposed via rclpy, like the expand topic name function:

https://github.com/ros2/rclpy/blob/91f7782619b1ccd9c812012ff85f6336186baab9/rclpy/rclpy/expand_topic_name.py#L18-L33

**Comment by Karsten1987** [comment]
So my referenced function does actually not really help. It does pretty much the opposite. I guess I stick with my reasoning then that the rcl solution would be preferred but given the time I think it's not feasible.

**Comment by Karsten1987** [comment]
I just introduced a new small function in `ros2node` called `get_absolute_node_name`. It's really just checking for the leading slash because I think we can all agree that a real node name expansion function should be there at one point (I'll create a ticket for it).

@wjwwood @jacobperron please iterate one more time over this. Also feel free to directly push on this ticket if you see room for improvement :)
thanks!

**Comment by nuclearsandwich** [comment]
Whs the `ros2 node info` verb intentionally omitted from this feature?

https://github.com/ros2/ros2cli/blob/aa832722af1c6295eb4b55951b5cd6a50c25108e/ros2node/ros2node/verb/info.py

**Pull request merged**
