### PR TITLE
ros2 param dump should handle empty list as exception.

### PR DESCRIPTION
**Pull request by fujitatomoya**
address https://github.com/ros2/ros2/issues/1517

### CODE REVIEW

**Review by fujitatomoya — COMMENTED** [review]
now `rclpy` behavior is consistent with `rclcpp`.

- `rclcpp` as reference

```cpp
  descriptor.dynamic_typing = true;
  descriptor.type = rclcpp::ParameterType::PARAMETER_NOT_SET;
  node->declare_parameter(
    "param_2_cpp",
    rclcpp::ParameterValue{},
    descriptor);
```

```bash
root@tomoyafujita:~/ros2_ws/colcon_ws# ros2 param dump /param_demo_cpp
/param_demo_cpp:
  ros__parameters:
    param_1_cpp: param_1_default_value_cpp
    param_2_cpp: null
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    start_type_description_service: true
    use_sim_time: false
root@tomoyafujita:~/ros2_ws/colcon_ws# ros2 param get /param_demo_cpp param_1_cpp
String value is: param_1_default_value_cpp
root@tomoyafujita:~/ros2_ws/colcon_ws# ros2 param get /param_demo_cpp param_2_cpp
Parameter not set.
root@tomoyafujita:~/ros2_ws/colcon_ws# ros2 param describe /param_demo_cpp param_1_cpp
Parameter name: param_1_cpp
  Type: string
  Constraints:
root@tomoyafujita:~/ros2_ws/colcon_ws# ros2 param describe /param_demo_cpp param_2_cpp
Parameter name: param_2_cpp
  Type: not set
  Constraints:
```

- `rclpy`

```python
        self.declare_parameter(
            "param_2",
            #value=ParameterValue(),
            descriptor=ParameterDescriptor(type=ParameterType.PARAMETER_NOT_SET, dynamic_typing=True),
        )
````

```bash
root@tomoyafujita:~/ros2_ws/colcon_ws# ros2 param dump /param_demo
/param_demo:
  ros__parameters:
    param_1: param_1_default_value
    param_2: null
    start_type_description_service: true
    use_sim_time: false
root@tomoyafujita:~/ros2_ws/colcon_ws# ros2 param get /param_demo param_1
String value is: param_1_default_value
root@tomoyafujita:~/ros2_ws/colcon_ws# ros2 param get /param_demo param_2
Parameter not set.
root@tomoyafujita:~/ros2_ws/colcon_ws# ros2 param describe /param_demo param_1
Parameter name: param_1
  Type: string
  Constraints:
root@tomoyafujita:~/ros2_ws/colcon_ws# ros2 param describe /param_demo param_2
Parameter name: param_2
  Type: not set
  Constraints:
```

**Review by wjwwood — APPROVED** [review]
lgtm, though I'm not 100% confident that the tool should throw here, rather than print something noting the issue. I'm just thinking of a new client library which doesn't handle the service call correctly, and whether or not it's a good idea for the tool to crash at that point or print a message pointing out the issue but otherwise continuing.

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20251/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14667/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/20975/)

**Comment by fujitatomoya** [comment]
@Mergifyio backport iron humble

**Comment by fujitatomoya** [comment]
@clalancette @wjwwood do you think we should backport this? this changes exception into stderr print.

or maybe we can do is, we keep the exception but mitigate [original issue](https://github.com/ros2/ros2/issues/1517) with handling `None` for iron and humble? i would like to have opinion on this.

**Pull request merged**
