### PR TITLE
[Humble] Add support use_sim_time for ros2 topic hz/bw/pub.

### PR DESCRIPTION
**Pull request by fujitatomoya**
humble backport of https://github.com/ros2/ros2cli/pull/754

### CODE REVIEW

**Review by fujitatomoya — COMMENTED** [review]
lgtm

**Comment by fujitatomoya** [comment]
@llapx requesting your review, since you are original author on this change.

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17615/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12158/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18185/)

**Comment by fujitatomoya** [comment]
https://ci.ros2.org/job/ci_windows/18185/cmake/new/ is unrelated.

**Review by ivanpauno — APPROVED** [review]

**Comment by gbiggs** [comment]
There are some test failures in the PR job. Please check them.

**Comment by llapx** [comment]
I see most of FAILTURES not related to this merge, can anyone help to have a check?

**Comment by ivanpauno** [comment]
@ros-pull-request-builder retest this please

**Pull request merged**
