### PR TITLE
Handle None Result #645

### PR DESCRIPTION
**Pull request by iwmq**
Fix https://github.com/ros2/ros2cli/issues/645

### CODE REVIEW

**Review by fujitatomoya — APPROVED** [review]
looks good to me

**Review by audrow — APPROVED** [review]
Looks good with green CI and a happy PR job.

**Comment by audrow** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14734/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9485/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12399/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14880/)

**Comment by audrow** [comment]
@ros-pull-request-builder retest this please

**Comment by audrow** [comment]
Thanks for the PR @iwmq!

**Comment by fujitatomoya** [comment]
@Mergifyio backport humble galactic foxy

**Pull request merged**
