### PR TITLE
Move rosidl implementation details to rosidl_runtime_py

### PR DESCRIPTION
**Pull request by jacobperron**
Implementation has been moved and refactored in https://github.com/ros2/rosidl_runtime_py/pull/3
This resolves several TODOs (5b54d70).

Also, using the abstracted functions it's easier to remove dependencies on packages deprecated in #363 (b01c63f).

Depends on  https://github.com/ros2/rosidl_runtime_py/pull/3

### CODE REVIEW

**Comment by jacobperron** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8468/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4359/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6881/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8369/)

**Comment by mjcarroll** [comment]
Does this need to land before #363 ?

**Comment by jacobperron** [comment]
> Does this need to land before #363 ?

No, this is a follow-up.

**Comment by jacobperron** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8471/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4361/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6883/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8371/)

**Pull request merged**
