### PR TITLE
add ros2 pkg executables

### LINKED ISSUE #21: Add a command to list all of the executables in a pkg
Currently, the `ros2 pkg` command has a way to list all packages, but not a way to list all executables that are available in a package.  I think it would be a good idea to be able to list all of the executables to make it easier for the user to find that list.

### PR DESCRIPTION
**Pull request by dirk-thomas**
Fixes #21.

I ran the nosetests locally rather than triggering full CI builds.

Ready for review.

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Related to this: this function would be very useful to have available for launchfiles (rather than https://github.com/ros2/turtlebot2_demo/pull/46/files#diff-cbb1fb4c24441aafc45b0e5bd453b316R37).
Do we want launchfile to depend on this package or should this function moved to a package lower in the stack ?

**Comment by dirk-thomas** [comment]
The Python module `api` within each of these packages is supposed to provide a stable API to be consumed by other packages. So yes, other packages can depend on e.g. `ros2pkg` to use it.

**Comment by wjwwood** [comment]
I think it would be better if every package that has a launch file doesn't need to depend on the command line tool (doesn't make a whole lot of sense imo). So I would be in favor of a shared location for the logic and have both the launch files and command line tool use that.

That being said, we can ticket it and fix it later.

**Comment by mikaelarguedas** [comment]
I agree with @wjwwood, I'm fine with adressing it now or later. As soon as we have consensus of the state it'll be in the beta I'll update the launchfiles accordingly

**Comment by dirk-thomas** [comment]
All cli packages have an API module atm. A refactoring like this should be considered for after the beta 2.

**Comment by dirk-thomas** [comment]
Waiting for review.

**Comment by mikaelarguedas** [comment]
code looks good, I'm about to try it with some changes depending on it. Will approve once it's tested

**Comment by mikaelarguedas** [comment]
Maybe it's me not understanding what the initial request was but I was expecting a list of executable names not their absolute path. I think this should be either
-  changes the behavior to give a list of basenames
- update the help message to states it's returning paths

I'd vote for the first one

**Comment by dirk-thomas** [comment]
Getting from the full path to the filename is trivial. Getting from the filename to the full path is not possible (without using the code from these Python modules). Therefore I would argue this verb **must** be able to return the full paths.

It would be ok to have an option to only return the filenames. Or showing the filename by default and having an option for showing the full path.

**Comment by mikaelarguedas** [comment]
> Or showing the filename by default and having an option for showing the full path.

:+1:

**Comment by dirk-thomas** [comment]
Added in 10f3be9ced31ce7c2cd954ae862e897afdeb7dfa.

Note when printing the basenames of the executables across all packages they are sorted by package name and only as a secondary criteria by the basename. Not sure if that should be a global sort instead.

**Comment by mikaelarguedas** [comment]
I think it does make sense to print them sorted by package name. I'm wondering if we have a way to hint the package it's coming from to the user ( it will make it easier to know what the corresponding ros2 run invocation would be).

**Comment by dirk-thomas** [comment]
The script could print each line as `pkg-name executable-basename` if no package name was specified?

**Comment by mikaelarguedas** [comment]
yeah that would be great

**Comment by dirk-thomas** [comment]
Please try the updated patch: 05b8116eec11262df4e97a73a5a81e79b28e925d

**Comment by mikaelarguedas** [comment]
New patch works fine. Do you think that the help or the output should add explaination of what the output means ? (I mean indicating that its in the form `<PACKAGE_NAME> <EXECUTABLE_NAME>`)

**Comment by dirk-thomas** [comment]
> Do you think that the help or the output should add explaination of what the output means ?

I would think it should be clear. Please feel free to propose anything specific.

**Comment by mikaelarguedas** [comment]
I don't have a great idea hence the question. Feel free to merge it as is and we can iterate on it if we find a clarification is needed and a good way to carry the additional information

**Pull request merged**
