### PR TITLE
add daemon command with verbs status, start, stop

### PR DESCRIPTION
**Pull request by dirk-thomas**
Addresses #34.

### CODE REVIEW

**Comment by Kukanani** [comment]
LGTM, confirmed working on Win 10.

Would it be useful to add some context to the help output, explaining what the daemon is/does? Maybe just a pointer to documentation, if such documentation exists.

**Comment by clalancette** [comment]
This also works for me on Linux.  There's a couple of overall things that would make this nicer:

1.  In all of the sub-commands, it would be nice to tell the user which ros-domain-id we are starting/stopping/statusing the daemon.
1.  Starting and stopping the daemon for a particular domain id is controlled through the environment variable ROS_DOMAIN_ID.  How do we control the rmw_implementation?  It would be nice to document how to control both of these somewhere.

**Comment by dirk-thomas** [comment]
Thanks for testing. More documentation is always nice. I am not sure I will add it right now though. If you have specific ideas what to add please consider making a PR.

The rmw impl. is selected by the environment variable `RMW_IMPLEMENTATION`. If not set a default is being selected. So "normal" users will only use one rmw impl at a time I don't think it needs exposure in the tool atm.

**Comment by mikaelarguedas** [comment]
> Starting and stopping the daemon for a particular domain id is controlled through the environment variable ROS_DOMAIN_ID. How do we control the rmw_implementation? It would be nice to document how to control both of these somewhere.

I think both of them (`ROS_DOMAIN_ID` and `RMW_IMPLEMENTATION`) should be documented globally because they apply to every ROS2 executable and not only this tool. For now the rmw information is documented in the [Working-with-multiple-RMW-implementations](https://github.com/ros2/ros2/wiki/Working-with-multiple-RMW-implementations) wiki page

**Comment by dirk-thomas** [comment]
Merging this for now as is. With potential improvements coming in the future.

**Comment by dirk-thomas** [comment]
Follow up fix in 45bbfab5f717388b89a9cf85c3220b66c5c523fc

**Pull request merged**
