### PR TITLE
remove deprecated options

### PR DESCRIPTION
**Pull request by fujitatomoya**
just removing options which have been deprecated for humble.

### CODE REVIEW

**Comment by fujitatomoya** [comment]
@clalancette @audrow can you do review?

**Review by clalancette — APPROVED** [review]
This looks good to me, but let's make sure to run CI with `--packages-above-and-dependencies ros2param ros2topic` just to make sure there are no tests depending on this behavior.

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18563/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13108/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19299/)

**Review by audrow — APPROVED** [review]
Looks good to me!

**Comment by fujitatomoya** [comment]
@clalancette @audrow do we need to add this Iron Release Note?

**Comment by clalancette** [comment]
> @clalancette @audrow do we need to add this Iron Release Note?

Yeah, that's a good idea.

**Pull request merged**
