### PR TITLE
[galactic] Improve performance of commands for Foxy on Windows by 4x (#686)

### PR DESCRIPTION
**Pull request by jacobperron**
Port #686 to Galactic.

### CODE REVIEW

**Comment by jacobperron** [comment]
I think this is the last change outstanding to fix https://github.com/ros2/ros2cli/issues/637 for all current distros.

**Review by audrow — APPROVED** [review]
Looks good to me!

**Comment by jacobperron** [comment]
@ros-pull-request-builder retest this please

**Comment by jacobperron** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17033/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11594/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17455/)

**Comment by clalancette** [comment]
Galactic is now EOL, so closing.

**Pull request closed without merging**
