### PR TITLE
Extend timeout to shutdown the command line process.

### PR DESCRIPTION
**Pull request by fujitatomoya**
address flaky test: https://github.com/ros2/ros2cli/issues/772

Signed-off-by: Tomoya Fujita <Tomoya.Fujita@sony.com>

### CODE REVIEW

**Comment by fujitatomoya** [comment]
@Blast545 @Crola1702 friendly ping

CC: @llapx

**Review by Crola1702 — APPROVED** [review]
LGTM

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17818/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12385/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18483/)

**Review by fujitatomoya — COMMENTED** [review]
thanks for the review, i will merge this with green CI.

**Comment by fujitatomoya** [comment]
@Mergifyio backport humble

**Pull request merged**
