### PR TITLE
also provide --include-hidden-services for `ros2 service list` verb

### PR DESCRIPTION
**Pull request by Karsten1987**
There's currently API in place for listing hidden services, however the command line option was never exposed.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The argument is already defined on the `service` command level: https://github.com/ros2/ros2cli/blob/95bfb056df795b6eef8bb73b165db31fcf2d867a/ros2service/ros2service/command/service.py#L24-L26

Otherwise the existing code using `args.include_hidden_services` would have failed.

**Comment by Karsten1987** [comment]
I see. 

It feels weird and inconsistent to me though that `ros2 service --include-hidden-services list` works while `ros2 service list --include-hidden-services` fails.
Also `ros2 service list -h` doesn't mention the option whereas other verbs like `find` explicitly make use of it.

**Comment by dirk-thomas** [comment]
> whereas other verbs like `find` explicitly make use of it.

You could add it in the same way as it is done in the `find` verb: https://github.com/ros2/ros2cli/blob/95bfb056df795b6eef8bb73b165db31fcf2d867a/ros2service/ros2service/verb/find.py#L33-L36

**Comment by Karsten1987** [comment]
What's the difference to what was proposed in this PR?

**Comment by dirk-thomas** [comment]
The comment clarifying that this is a know duplication.

**Comment by Karsten1987** [comment]
comment added in 5a41e56

**Comment by Karsten1987** [comment]
I'll have to look into the regression introduced from the failing tests below. Don't know right off the bat what's happening there.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11387/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6610/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9336/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11280/)

**Comment by homalozoa** [comment]
Friendly ping.

**Comment by fujitatomoya** [comment]
@ros-pull-request-builder retest this please

**Review by fujitatomoya — APPROVED** [review]

**Comment by fujitatomoya** [comment]
@ros-pull-request-builder retest this please

**Review by audrow — APPROVED** [review]
Looks good with green CI.

**Comment by fujitatomoya** [comment]
CI(retry):
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16296/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10916/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16663/)

**Pull request merged**
