### PR TITLE
ros2pkg warning message typo fix.

### PR DESCRIPTION
**Pull request by fujitatomoya**
part of https://github.com/osrf/ros2_test_cases/issues/954

### CODE REVIEW

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18689/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13215/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19419/)

**Comment by clalancette** [comment]
(we'll also want to backport this one to Iron)

**Comment by fujitatomoya** [comment]
@Mergiryio backport iron

**Comment by fujitatomoya** [comment]
@Mergifyio backport iron

**Pull request merged**
